### ISSUE TITLE
Error in parsing CSS

### ISSUE THREAD

**Issue by BA1RY** [product-ride/styled-wind#15]
**Describe the bug**
Normal CSS styles are not parsed properly.

**Screenshots:**

**Code:**
![3](https://user-images.githubusercontent.com/10570968/100078489-95869100-2e69-11eb-9900-d1567747f067.png)

**Output:**
The above CSS is parsed as `background: redcolor:yellow;`.

![4](https://user-images.githubusercontent.com/10570968/100078530-a0d9bc80-2e69-11eb-826d-ba1811e69075.png)

On reversing the above order, it's parsed as `color: yellowbackground:red;` 

**Expected behavior**
It should be parsed as ` background: red; color: yellow;`

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Brave

**Comment by vilvaathibanpb** [comment]
Sure Vignesh. @devevignesh . Also, @BA1RY is this the latest version of styled-wind?

**Comment by BA1RY** [comment]
@vilvaathibanpb Yes, this is in v0.0.0-beta.9

**Comment by devevignesh** [comment]
@vilvaathibanpb @ameerthehacker I debug the issue and found that while parsing, an array of strings are split into substrings using the `;` separator (const classes = stringsPart.split(';')) which cause the semicolon is missing at the end of the style element. So that the style wind style will be applied in the same line. 

I'm assuming that the classes which are not defined in `staticClasses` will cause the same error. For example: `background: red` and `color: yellow`. Please correct me if I'm wrong.

**Comment by vilvaathibanpb** [comment]
@devevignesh your finding is right. Make sure if the string doesn't start with `.` or `swind`, add a `;` at the end. this should solve the issue

**Comment by ameerthehacker** [comment]
@devevignesh this is a bug.
